ktor:
    application:
        modules:
            - com.libreguardia.ApplicationKt.main
    deployment:
        port: 8080
storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/libreguardia"
    user: "postgres"
    password: "libreguardia"
#Implementar connection pool