package com.libreguardia.exception

enum class ErrorCode {
    ROLE_NOT_FOUND,
    USER_NOT_FOUND,
    INCORRECT_PASSWORD,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    INVALID_SESSION,
    INSUFFICIENT_PERMISSIONS,
    DUPLICATED_UNIQUE_FIELD,
    BAD_REQUEST,
    UNKNOWN_SERVER_ERROR,
    ACADEMIC_YEAR_NOT_FOUND,
    PROFESSIONAL_FAMILY_NOT_FOUND
}