spring.application.name=libreguardia

# PostgreSQL
#THIS DATA SHOULD BE STORED APART, IN A FILE OUTSIDE FROM THE APP,
#THEN THE APP WILL RETRIEVE IT FROM THAT FILE
###
spring.datasource.url=jdbc:postgresql://localhost:5432/libreguardia
spring.datasource.username=postgres
spring.datasource.password=libreguardia
###
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Spring logs
logging.level.org.springframework.security=DEBUG

#Spring virtual threads, to enable non-blocking operations
spring.threads.virtual.enabled=true